AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal test template for basic VPC infrastructure

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment identifier
    Default: test-env

  VpcCIDR:
    Type: String
    Description: CIDR block for the VPC
    Default: 10.0.0.0/16

  ClusterName:
    Type: String
    Description: Name of the cluster
    Default: test-cluster

  ClusterType:
    Type: String
    Description: Type of cluster
    Default: shared
    AllowedValues:
      - Shared
      - Dedicated

  ClusterEnvironment:
    Type: String
    Description: Environment of cluster
    Default: Dev
    AllowedValues:
      - Production
      - Staging
      - Dev

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref ClusterName
        - Key: Type
          Value: !Ref ClusterType
        - Key: Environment
          Value: !Ref ClusterEnvironment

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-InternetGateway

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PublicSubnet-AZ1

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PublicRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

Outputs:
  VPC:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub ${EnvironmentName}-VPC

  TemplateVersion:
    Description: CloudFormation template version
    Value: "1.0.0"