AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Main shared cluster template that orchestrates infrastructure and database deployment
  using nested CloudFormation stacks. This keeps individual templates small
  while deploying everything together as a single unit.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Configuration"
        Parameters:
          - EnvironmentName
      - Label:
          default: "Network Configuration"
        Parameters:
          - VpcCIDR
          - AvailabilityZoneCount
      - Label:
          default: "Private App Zone Subnets"
        Parameters:
          - PrivateAppSubnet1CIDR
          - PrivateAppSubnet2CIDR
          - PrivateAppSubnet3CIDR
      - Label:
          default: "Private DB Zone Subnets"
        Parameters:
          - PrivateDBSubnet1CIDR
          - PrivateDBSubnet2CIDR
          - PrivateDBSubnet3CIDR
      - Label:
          default: "Template Configuration"
        Parameters:
          - TemplateS3Bucket
          - TemplateS3KeyPrefix
      - Label:
          default: "Resource Tagging"
        Parameters:
          - ProjectName
          - CostCenter
          - Owner
    ParameterLabels:
      EnvironmentName:
        default: "Environment Name"
      VpcCIDR:
        default: "VPC CIDR Block"
      AvailabilityZoneCount:
        default: "Number of Availability Zones"

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment identifier (e.g., prod, staging, dev)
    MinLength: 1
    MaxLength: 50
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9-]*$
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters and hyphens

  VpcCIDR:
    Type: String
    Description: CIDR block for the VPC
    Default: 10.0.0.0/16
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid CIDR block in the format x.x.x.x/x

  AvailabilityZoneCount:
    Type: Number
    Description: Number of Availability Zones to use (2 or 3)
    Default: 2
    AllowedValues:
      - 2
      - 3
    ConstraintDescription: Must be 2 or 3

  PrivateAppSubnet1CIDR:
    Type: String
    Description: CIDR block for Private App Subnet in Availability Zone 1
    Default: 10.0.1.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid CIDR block in the format x.x.x.x/x

  PrivateAppSubnet2CIDR:
    Type: String
    Description: CIDR block for Private App Subnet in Availability Zone 2
    Default: 10.0.2.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid CIDR block in the format x.x.x.x/x

  PrivateAppSubnet3CIDR:
    Type: String
    Description: CIDR block for Private App Subnet in Availability Zone 3
    Default: 10.0.3.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid CIDR block in the format x.x.x.x/x

  PrivateDBSubnet1CIDR:
    Type: String
    Description: CIDR block for Private DB Subnet in Availability Zone 1
    Default: 10.0.11.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid CIDR block in the format x.x.x.x/x

  PrivateDBSubnet2CIDR:
    Type: String
    Description: CIDR block for Private DB Subnet in Availability Zone 2
    Default: 10.0.12.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid CIDR block in the format x.x.x.x/x

  PrivateDBSubnet3CIDR:
    Type: String
    Description: CIDR block for Private DB Subnet in Availability Zone 3
    Default: 10.0.13.0/24
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid CIDR block in the format x.x.x.x/x

  TemplateS3Bucket:
    Type: String
    Description: S3 bucket containing the nested CloudFormation templates
    MinLength: 1
    ConstraintDescription: Must specify the S3 bucket name

  TemplateS3KeyPrefix:
    Type: String
    Description: S3 key prefix for nested templates (optional)
    Default: ""

  ProjectName:
    Type: String
    Description: Optional project name for resource tagging
    Default: ""
    MaxLength: 100

  CostCenter:
    Type: String
    Description: Optional cost center identifier for resource tagging
    Default: ""
    MaxLength: 100

  Owner:
    Type: String
    Description: Optional owner or team name for resource tagging
    Default: ""
    MaxLength: 100

  # Application Configuration
  CodeBucketName:
    Type: String
    Description: S3 bucket name containing lambda-api.zip (from cluster code_bucket field)
    Default: manual-api-code-bucket
    MinLength: 1
    ConstraintDescription: Must specify the code bucket name

  AppName:
    Type: String
    Default: flowrix
    Description: Application name for resource naming

  Stage:
    Type: String
    Default: prod
    Description: Deployment stage (prod, staging, dev)

  QueueName:
    Type: String
    Default: prod-sqs
    Description: SQS queue name for Laravel job processing

  # Bref Layer Configuration
  BrefLayerArn:
    Type: String
    Description: Bref PHP layer ARN for the deployment region
    MinLength: 1
    ConstraintDescription: Must specify the Bref PHP layer ARN

  # Multi-tenant domain configuration
  CustomDomainName:
    Type: String
    Description: Custom domain name for CloudFront (e.g., *.flowrix.app for multi-tenant)
    Default: "*.flowrix.app"
    MaxLength: 255

  CertificateArn:
    Type: String
    Description: ACM certificate ARN for wildcard domain (*.flowrix.app)
    Default: "arn:aws:acm:us-east-1:078607863013:certificate/d0097bd1-e417-4057-9747-24b0d81885f8"
    MinLength: 1
    ConstraintDescription: Must provide ACM certificate ARN for *.flowrix.app

  # Cluster-specific parameters for tagging
  ClusterName:
    Type: String
    Description: Name of the cluster for resource tagging
    MinLength: 1
    MaxLength: 255

  ClusterType:
    Type: String
    Description: Type of cluster (Shared or Dedicated) for resource tagging
    AllowedValues:
      - Shared
      - Dedicated
    ConstraintDescription: Must be either Shared or Dedicated

  ClusterEnvironment:
    Type: String
    Description: Environment of cluster (Production, Staging, or Dev) for resource tagging
    AllowedValues:
      - Production
      - Staging
      - Dev
    ConstraintDescription: Must be Production, Staging, or Dev

Conditions:
  # Condition to determine if we should use Availability Zone 3
  UseAZ3: !Equals [!Ref AvailabilityZoneCount, 3]
  
  # Conditions for optional custom tags
  HasProjectName: !Not [!Equals [!Ref ProjectName, '']]
  HasCostCenter: !Not [!Equals [!Ref CostCenter, '']]
  HasOwner: !Not [!Equals [!Ref Owner, '']]
  
  # Condition for S3 key prefix
  HasTemplatePrefix: !Not [!Equals [!Ref TemplateS3KeyPrefix, '']]

Resources:
  # ==========================================
  # Infrastructure Nested Stack
  # ==========================================
  
  InfrastructureStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${TemplateS3Bucket}.s3.${AWS::Region}.amazonaws.com/${Prefix}shared-infrastructure-template.yaml'
        - Prefix: !If [HasTemplatePrefix, !Sub '${TemplateS3KeyPrefix}/', '']
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcCIDR: !Ref VpcCIDR
        AvailabilityZoneCount: !Ref AvailabilityZoneCount
        PrivateAppSubnet1CIDR: !Ref PrivateAppSubnet1CIDR
        PrivateAppSubnet2CIDR: !Ref PrivateAppSubnet2CIDR
        PrivateAppSubnet3CIDR: !Ref PrivateAppSubnet3CIDR
        PrivateDBSubnet1CIDR: !Ref PrivateDBSubnet1CIDR
        PrivateDBSubnet2CIDR: !Ref PrivateDBSubnet2CIDR
        PrivateDBSubnet3CIDR: !Ref PrivateDBSubnet3CIDR
        ProjectName: !Ref ProjectName
        CostCenter: !Ref CostCenter
        Owner: !Ref Owner
        ClusterName: !Ref ClusterName
        ClusterType: !Ref ClusterType
        ClusterEnvironment: !Ref ClusterEnvironment
      Tags:
        - Key: Name
          Value: !Sub ${ClusterName}-Infrastructure
        - Key: Type
          Value: !Ref ClusterType
        - Key: Environment
          Value: !Ref ClusterEnvironment
        - Key: StackType
          Value: Infrastructure
        - Key: ManagedBy
          Value: CloudFormation
        - !If
          - HasProjectName
          - Key: Project
            Value: !Ref ProjectName
          - !Ref AWS::NoValue
        - !If
          - HasCostCenter
          - Key: CostCenter
            Value: !Ref CostCenter
          - !Ref AWS::NoValue
        - !If
          - HasOwner
          - Key: Owner
            Value: !Ref Owner
          - !Ref AWS::NoValue

  # ==========================================
  # Application Nested Stack
  # ==========================================
  
  ApplicationStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: InfrastructureStack
    Properties:
      TemplateURL: !Sub
        - 'https://${TemplateS3Bucket}.s3.${AWS::Region}.amazonaws.com/${Prefix}shared-app-template.yaml'
        - Prefix: !If [HasTemplatePrefix, !Sub '${TemplateS3KeyPrefix}/', '']
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        CodeBucketName: !Ref CodeBucketName
        AppName: !Ref AppName
        Stage: !Ref Stage
        QueueName: !Ref QueueName
        BrefLayerArn: !Ref BrefLayerArn
        ProjectName: !Ref ProjectName
        CostCenter: !Ref CostCenter
        Owner: !Ref Owner
        ClusterName: !Ref ClusterName
        ClusterType: !Ref ClusterType
        ClusterEnvironment: !Ref ClusterEnvironment
      Tags:
        - Key: Name
          Value: !Sub ${ClusterName}-Application
        - Key: Type
          Value: !Ref ClusterType
        - Key: Environment
          Value: !Ref ClusterEnvironment
        - Key: StackType
          Value: Application
        - Key: ManagedBy
          Value: CloudFormation
        - !If
          - HasProjectName
          - Key: Project
            Value: !Ref ProjectName
          - !Ref AWS::NoValue
        - !If
          - HasCostCenter
          - Key: CostCenter
            Value: !Ref CostCenter
          - !Ref AWS::NoValue
        - !If
          - HasOwner
          - Key: Owner
            Value: !Ref Owner
          - !Ref AWS::NoValue

  # ==========================================
  # Edge Deployment Nested Stack
  # ==========================================
  
  EdgeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ApplicationStack
    Properties:
      TemplateURL: !Sub
        - 'https://${TemplateS3Bucket}.s3.${AWS::Region}.amazonaws.com/${Prefix}shared-edge-template.yaml'
        - Prefix: !If [HasTemplatePrefix, !Sub '${TemplateS3KeyPrefix}/', '']
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ApiGatewayDomainName: !GetAtt ApplicationStack.Outputs.ApiGatewayDomainName
        CustomDomainName: !Ref CustomDomainName
        CertificateArn: !Ref CertificateArn
        ProjectName: !Ref ProjectName
        CostCenter: !Ref CostCenter
        Owner: !Ref Owner
        ClusterName: !Ref ClusterName
        ClusterType: !Ref ClusterType
        ClusterEnvironment: !Ref ClusterEnvironment
      Tags:
        - Key: Name
          Value: !Sub ${ClusterName}-Edge
        - Key: Type
          Value: !Ref ClusterType
        - Key: Environment
          Value: !Ref ClusterEnvironment
        - Key: StackType
          Value: Edge
        - Key: ManagedBy
          Value: CloudFormation
        - !If
          - HasProjectName
          - Key: Project
            Value: !Ref ProjectName
          - !Ref AWS::NoValue
        - !If
          - HasCostCenter
          - Key: CostCenter
            Value: !Ref CostCenter
          - !Ref AWS::NoValue
        - !If
          - HasOwner
          - Key: Owner
            Value: !Ref Owner
          - !Ref AWS::NoValue

Outputs:
  # Main Stack Outputs
  MainStackId:
    Description: Main cluster stack ID
    Value: !Ref AWS::StackId

  InfrastructureStackId:
    Description: Infrastructure nested stack ID
    Value: !Ref InfrastructureStack

  ApplicationStackId:
    Description: Application nested stack ID
    Value: !Ref ApplicationStack

  EdgeStackId:
    Description: Edge nested stack ID
    Value: !Ref EdgeStack

  # Infrastructure Outputs (passed through from nested stack)
  VPC:
    Description: VPC ID
    Value: !GetAtt InfrastructureStack.Outputs.VPC

  VPCCidr:
    Description: VPC CIDR block
    Value: !GetAtt InfrastructureStack.Outputs.VPCCidr

  PrivateAppSubnets:
    Description: Comma-delimited list of Private App Subnet IDs
    Value: !GetAtt InfrastructureStack.Outputs.PrivateAppSubnets

  PrivateDBSubnets:
    Description: Comma-delimited list of Private DB Subnet IDs
    Value: !GetAtt InfrastructureStack.Outputs.PrivateDBSubnets

  LambdaSecurityGroup:
    Description: Lambda Security Group ID for Private App Zone
    Value: !GetAtt InfrastructureStack.Outputs.LambdaSecurityGroup

  DBSecurityGroup:
    Description: DB Security Group ID for Private DB Zone
    Value: !GetAtt InfrastructureStack.Outputs.DBSecurityGroup

  NATGateway:
    Description: NAT Gateway ID for Lambda internet access
    Value: !GetAtt InfrastructureStack.Outputs.NATGateway

  # Application Outputs (passed through from nested stack)
  ApiUrl:
    Description: HTTP API endpoint
    Value: !GetAtt ApplicationStack.Outputs.ApiUrl

  WebFunctionName:
    Description: Lambda function name (web)
    Value: !GetAtt ApplicationStack.Outputs.WebFunctionName

  WorkerFunctionName:
    Description: Lambda function name (worker)
    Value: !GetAtt ApplicationStack.Outputs.WorkerFunctionName

  ArtisanFunctionName:
    Description: Lambda function name (artisan)
    Value: !GetAtt ApplicationStack.Outputs.ArtisanFunctionName

  QueueUrl:
    Description: SQS queue URL
    Value: !GetAtt ApplicationStack.Outputs.QueueUrl

  PrivateBucketName:
    Description: Private data bucket name
    Value: !GetAtt ApplicationStack.Outputs.PrivateBucketName

  # Edge Outputs (passed through from nested stack)
  CloudFrontDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt EdgeStack.Outputs.CloudFrontDomainName

  FrontendAssetsBucketName:
    Description: S3 bucket name for frontend assets
    Value: !GetAtt EdgeStack.Outputs.FrontendAssetsBucketName

  ProductionPortalUrl:
    Description: Production portal URL (root domain)
    Value: !GetAtt EdgeStack.Outputs.ProductionPortalUrl

  DevPortalUrl:
    Description: Development portal URL
    Value: !GetAtt EdgeStack.Outputs.DevPortalUrl

  EdgeApiUrl:
    Description: API URL through CloudFront
    Value: !GetAtt EdgeStack.Outputs.EdgeApiUrl

  WebACLArn:
    Description: WAF Web ACL ARN
    Value: !GetAtt EdgeStack.Outputs.WebACLArn

  # Template metadata
  TemplateVersion:
    Description: CloudFormation template version
    Value: "1.0.0"

  DeploymentArchitecture:
    Description: Deployment architecture used
    Value: "Nested Stacks (Infrastructure + Application + Edge)"