AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Basic VPC network infrastructure without Aurora MySQL.
  Creates a three-zone architecture (Public, Private App, Private DB) with configurable
  parameters for flexibility across different deployment scenarios.

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment identifier (e.g., prod, staging, dev)
    MinLength: 1
    MaxLength: 50
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9-]*$
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters and hyphens

  VpcCIDR:
    Type: String
    Description: CIDR block for the VPC
    Default: 10.0.0.0/16
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid CIDR block in the format x.x.x.x/x

  AvailabilityZoneCount:
    Type: Number
    Description: Number of Availability Zones to use (1, 2, or 3)
    Default: 2
    AllowedValues:
      - 1
      - 2
      - 3
    ConstraintDescription: Must be 1, 2, or 3

  ClusterName:
    Type: String
    Description: Name of the cluster for resource tagging
    MinLength: 1
    MaxLength: 255

  ClusterType:
    Type: String
    Description: Type of cluster (Shared or Dedicated) for resource tagging
    AllowedValues:
      - Shared
      - Dedicated
    ConstraintDescription: Must be either Shared or Dedicated

  ClusterEnvironment:
    Type: String
    Description: Environment of cluster (Production, Staging, or Dev) for resource tagging
    AllowedValues:
      - Production
      - Staging
      - Dev
    ConstraintDescription: Must be Production, Staging, or Dev

Conditions:
  UseAZ2: !Or
    - !Equals [!Ref AvailabilityZoneCount, 2]
    - !Equals [!Ref AvailabilityZoneCount, 3]
  
  UseAZ3: !Equals [!Ref AvailabilityZoneCount, 3]

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    DeletionPolicy: Delete
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref ClusterName
        - Key: Type
          Value: !Ref ClusterType
        - Key: Environment
          Value: !Ref ClusterEnvironment

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-InternetGateway

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Public Subnets
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [0, !Cidr [!Ref VpcCIDR, 6, 8]]
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PublicSubnet-AZ1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Condition: UseAZ2
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [1, !Cidr [!Ref VpcCIDR, 6, 8]]
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PublicSubnet-AZ2

  # Private App Subnets
  PrivateAppSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [2, !Cidr [!Ref VpcCIDR, 6, 8]]
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PrivateAppSubnet-AZ1

  PrivateAppSubnet2:
    Type: AWS::EC2::Subnet
    Condition: UseAZ2
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [3, !Cidr [!Ref VpcCIDR, 6, 8]]
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PrivateAppSubnet-AZ2

  # Private DB Subnets
  PrivateDBSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [4, !Cidr [!Ref VpcCIDR, 6, 8]]
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PrivateDBSubnet-AZ1

  PrivateDBSubnet2:
    Type: AWS::EC2::Subnet
    Condition: UseAZ2
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Select [5, !Cidr [!Ref VpcCIDR, 6, 8]]
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-PrivateDBSubnet-AZ2

  # Security Groups
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-AppSecurityGroup
      GroupDescription: Security group for application workloads
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: Allow HTTPS to internet
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-AppSecurityGroup

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-DBSecurityGroup
      GroupDescription: Security group for database resources
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-DBSecurityGroup

Outputs:
  VPC:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub ${EnvironmentName}-VPC

  VPCCidr:
    Description: VPC CIDR block
    Value: !GetAtt VPC.CidrBlock
    Export:
      Name: !Sub ${EnvironmentName}-VPC-CIDR

  PublicSubnets:
    Description: Comma-delimited list of Public Subnet IDs
    Value: !If
      - UseAZ2
      - !Sub "${PublicSubnet1},${PublicSubnet2}"
      - !Ref PublicSubnet1
    Export:
      Name: !Sub ${EnvironmentName}-PublicSubnets

  PrivateAppSubnets:
    Description: Comma-delimited list of Private App Subnet IDs
    Value: !If
      - UseAZ2
      - !Sub "${PrivateAppSubnet1},${PrivateAppSubnet2}"
      - !Ref PrivateAppSubnet1
    Export:
      Name: !Sub ${EnvironmentName}-PrivateAppSubnets

  PrivateDBSubnets:
    Description: Comma-delimited list of Private DB Subnet IDs
    Value: !If
      - UseAZ2
      - !Sub "${PrivateDBSubnet1},${PrivateDBSubnet2}"
      - !Ref PrivateDBSubnet1
    Export:
      Name: !Sub ${EnvironmentName}-PrivateDBSubnets

  AppSecurityGroup:
    Description: App Security Group ID
    Value: !Ref AppSecurityGroup
    Export:
      Name: !Sub ${EnvironmentName}-AppSecurityGroup

  DBSecurityGroup:
    Description: DB Security Group ID
    Value: !Ref DBSecurityGroup
    Export:
      Name: !Sub ${EnvironmentName}-DBSecurityGroup

  TemplateVersion:
    Description: CloudFormation template version
    Value: "1.0.0"