AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Shared cluster edge deployment stack - CloudFront distribution with WAF protection.
  Routes /api/* to API Gateway, serves Vue.js SPA from S3 (/portal/ and /dev-portal/).
  Includes WAF with best practices for PHP/Vue.js applications.

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment identifier (must match other stacks)
    MinLength: 1
    MaxLength: 50
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9-]*$
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters and hyphens

  # API Gateway endpoint (imported from app stack)
  ApiGatewayDomainName:
    Type: String
    Description: API Gateway domain name (without https://)
    MinLength: 1
    ConstraintDescription: Must specify the API Gateway domain name

  # Stage for API Gateway path
  Stage:
    Type: String
    Default: prod
    Description: API Gateway stage name
    MinLength: 1
    ConstraintDescription: Must specify the API Gateway stage

  # Custom domain configuration for multi-tenant setup
  CustomDomainName:
    Type: String
    Description: Custom domain name for CloudFront (e.g., *.flowrix.app)
    Default: "*.flowrix.app"
    MaxLength: 255

  CertificateArn:
    Type: String
    Description: ACM certificate ARN for wildcard domain (*.flowrix.app)
    Default: "arn:aws:acm:us-east-1:078607863013:certificate/d0097bd1-e417-4057-9747-24b0d81885f8"
    MinLength: 1
    ConstraintDescription: Must provide ACM certificate ARN for *.flowrix.app

  ProjectName:
    Type: String
    Description: Optional project name for resource tagging
    Default: ""
    MaxLength: 100

  CostCenter:
    Type: String
    Description: Optional cost center identifier for resource tagging
    Default: ""
    MaxLength: 100

  Owner:
    Type: String
    Description: Optional owner or team name for resource tagging
    Default: ""
    MaxLength: 100

  # Cluster-specific parameters for tagging
  ClusterName:
    Type: String
    Description: Name of the cluster for resource tagging
    MinLength: 1
    MaxLength: 255

  ClusterType:
    Type: String
    Description: Type of cluster (Shared or Dedicated) for resource tagging
    AllowedValues:
      - Shared
      - Dedicated
    ConstraintDescription: Must be either Shared or Dedicated

  ClusterEnvironment:
    Type: String
    Description: Environment of cluster (Production, Staging, or Dev) for resource tagging
    AllowedValues:
      - Production
      - Staging
      - Dev
    ConstraintDescription: Must be Production, Staging, or Dev

Conditions:
  # Conditions for optional custom tags
  HasProjectName: !Not [!Equals [!Ref ProjectName, '']]
  HasCostCenter: !Not [!Equals [!Ref CostCenter, '']]
  HasOwner: !Not [!Equals [!Ref Owner, '']]
  
  # Condition for custom domain (always true now since we have defaults)
  HasCustomDomain: !Not [!Equals [!Ref CustomDomainName, '']]
  
  # Condition for wildcard domain
  IsWildcardDomain: !Equals [!Ref CustomDomainName, '*.flowrix.app']

Resources:
  # ==========================================
  # Dedicated S3 Bucket for Frontend Assets
  # ==========================================
  
  FrontendAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Let CloudFormation auto-generate unique bucket name
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub ${ClusterName}-FrontendAssets
        - Key: Type
          Value: !Ref ClusterType
        - Key: Environment
          Value: !Ref ClusterEnvironment
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================
  # CloudFront Origin Access Control for S3
  # ==========================================
  
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${EnvironmentName}-s3-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
        Description: Origin Access Control for S3 bucket

  # ==========================================
  # CloudFront Distribution
  # ==========================================
  
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub ${EnvironmentName} Edge Distribution - Vue.js SPA + API Gateway
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_All
        
        # Custom domain configuration (wildcard support)
        # Note: For wildcard domains like *.flowrix.app, we can set the alias
        # CloudFront will accept any subdomain that matches the certificate
        Aliases:
          - "*.flowrix.app"
        
        ViewerCertificate: !If
          - HasCustomDomain
          - AcmCertificateArn: !Ref CertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        
        # Origins
        Origins:
          # S3 Origin for Vue.js frontend assets (dedicated bucket)
          - Id: S3Origin
            DomainName: !GetAtt FrontendAssetsBucket.RegionalDomainName
            OriginAccessControlId: !Ref OriginAccessControl
            S3OriginConfig:
              OriginAccessIdentity: ""
          
          # S3 Origin for production portal (with /portal prefix)
          - Id: S3PortalOrigin
            DomainName: !GetAtt FrontendAssetsBucket.RegionalDomainName
            OriginPath: /portal
            OriginAccessControlId: !Ref OriginAccessControl
            S3OriginConfig:
              OriginAccessIdentity: ""
          
          # API Gateway Origin for /api/* routes (no stage path)
          - Id: ApiGatewayOrigin
            DomainName: !Ref ApiGatewayDomainName
            CustomOriginConfig:
              HTTPPort: 443
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
            OriginCustomHeaders:
              - HeaderName: x-cloudfront-secret
                HeaderValue: cf-secret-a8b9c2d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6
        
        # Cache Behaviors
        CacheBehaviors:
          # API routes - no caching, forward all headers except host, custom header added
          - PathPattern: "/api/*"
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled
            OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf  # AllViewerExceptHostHeader
            Compress: false
          
          # Dev portal - Vue.js SPA (files are in /dev-portal/ folder in S3)
          - PathPattern: "/dev-portal/*"
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
            Compress: true
        
        # Default behavior - Production portal (uses S3PortalOrigin with /portal prefix)
        DefaultCacheBehavior:
          TargetOriginId: S3PortalOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          Compress: true
        
        # Custom error pages for SPA routing
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
      
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-cloudfront
        - Key: Type
          Value: !Ref ClusterType
        - Key: Environment
          Value: !Ref ClusterEnvironment
        - Key: ManagedBy
          Value: CloudFormation
        - !If
          - HasProjectName
          - Key: Project
            Value: !Ref ProjectName
          - !Ref AWS::NoValue
        - !If
          - HasCostCenter
          - Key: CostCenter
            Value: !Ref CostCenter
          - !Ref AWS::NoValue
        - !If
          - HasOwner
          - Key: Owner
            Value: !Ref Owner
          - !Ref AWS::NoValue

  # ==========================================
  # S3 Bucket Policy for CloudFront OAC
  # ==========================================
  
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendAssetsBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${FrontendAssetsBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}

Outputs:
  # S3 Frontend Bucket Outputs
  FrontendAssetsBucketName:
    Description: S3 bucket name for frontend assets
    Value: !Ref FrontendAssetsBucket
    Export:
      Name: !Sub ${EnvironmentName}-FrontendAssetsBucketName

  FrontendAssetsBucketArn:
    Description: S3 bucket ARN for frontend assets
    Value: !GetAtt FrontendAssetsBucket.Arn
    Export:
      Name: !Sub ${EnvironmentName}-FrontendAssetsBucketArn

  FrontendAssetsBucketDomainName:
    Description: S3 bucket regional domain name
    Value: !GetAtt FrontendAssetsBucket.RegionalDomainName
    Export:
      Name: !Sub ${EnvironmentName}-FrontendAssetsBucketDomainName

  # CloudFront Outputs
  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub ${EnvironmentName}-CloudFrontDistributionId

  CloudFrontDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub ${EnvironmentName}-CloudFrontDomainName

  CloudFrontDistributionArn:
    Description: CloudFront distribution ARN
    Value: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}
    Export:
      Name: !Sub ${EnvironmentName}-CloudFrontDistributionArn

  # WAF Outputs (Not used - WAF is only on API Gateway, not CloudFront)
  # WebACLId:
  #   Description: WAF Web ACL ID
  #   Value: !Ref WebACL
  #   Export:
  #     Name: !Sub ${EnvironmentName}-WebACLId

  # WebACLArn:
  #   Description: WAF Web ACL ARN
  #   Value: !GetAtt WebACL.Arn
  #   Export:
  #     Name: !Sub ${EnvironmentName}-WebACLArn

  # Access URLs (multi-tenant aware)
  ProductionPortalUrl:
    Description: Production portal URL (use tenant.flowrix.app for specific tenant)
    Value: !If
      - IsWildcardDomain
      - "https://[tenant].flowrix.app/"
      - !If
        - HasCustomDomain
        - !Sub https://${CustomDomainName}/
        - !Sub https://${CloudFrontDistribution.DomainName}/
    Export:
      Name: !Sub ${EnvironmentName}-ProductionPortalUrl

  DevPortalUrl:
    Description: Development portal URL (use tenant.flowrix.app/dev-portal/ for specific tenant)
    Value: !If
      - IsWildcardDomain
      - "https://[tenant].flowrix.app/dev-portal/"
      - !If
        - HasCustomDomain
        - !Sub https://${CustomDomainName}/dev-portal/
        - !Sub https://${CloudFrontDistribution.DomainName}/dev-portal/
    Export:
      Name: !Sub ${EnvironmentName}-DevPortalUrl

  ApiUrl:
    Description: API URL through CloudFront (use tenant.flowrix.app/api/ for specific tenant)
    Value: !If
      - IsWildcardDomain
      - "https://[tenant].flowrix.app/api/"
      - !If
        - HasCustomDomain
        - !Sub https://${CustomDomainName}/api/
        - !Sub https://${CloudFrontDistribution.DomainName}/api/
    Export:
      Name: !Sub ${EnvironmentName}-EdgeApiUrl

  # Multi-tenant configuration info
  WildcardDomainPattern:
    Description: Wildcard domain pattern for multi-tenant setup
    Value: "*.flowrix.app"
    Export:
      Name: !Sub ${EnvironmentName}-WildcardDomainPattern

  CertificateArnUsed:
    Description: ACM certificate ARN used for SSL
    Value: !Ref CertificateArn
    Export:
      Name: !Sub ${EnvironmentName}-CertificateArn

  # Template metadata
  TemplateVersion:
    Description: CloudFormation template version
    Value: "1.0.0"

  DeploymentArchitecture:
    Description: Edge deployment architecture
    Value: "CloudFront + S3 (Vue.js SPA) + API Gateway (WAF protection on API Gateway only)"