AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal test - VPC only

Parameters:
  EnvironmentName:
    Type: String
    Default: test-vpc
  ClusterName:
    Type: String
    Default: test-cluster
  ClusterType:
    Type: String
    Default: Shared
  ClusterEnvironment:
    Type: String
    Default: Dev

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref ClusterName

Outputs:
  VPC:
    Description: VPC ID
    Value: !Ref VPC
  
  TemplateVersion:
    Description: Template version
    Value: "1.0.0"